name: flutter_tsc
description: Flutter TSC Printer plugin.
version: 0.1.3
homepage: https://github.com/dolunay/FlutterTscPlugin

flutter:
  plugin:
    platforms:
      android:
        package: sg.alitec.flutter_tsc
        pluginClass: FlutterTscPlugin

environment:
  sdk: ">=3.2.0 <4.0.0"
  #flutter: ">=1.12.13+hotfix.5 <2.0.0"
  
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter